=== youssef-souilah/StockMaster/data/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">
  <xsi:element name="Products">
    <xsi:complexType>
      <xsi:sequence>
        <xsi:element name="Product" maxOccurs="unbounded">
          <xsi:complexType>
            <xsi:sequence>
              <xsi:element name="Name" type="xsi:string"/>
              <xsi:element name="Price" type="xsi:decimal"/>
              <xsi:element name="Category" type="xsi:string"/>
              <xsi:element name="Brand" type="xsi:string"/>
              <xsi:element name="Rating_Count" type="xsi:int"/>
              <xsi:element name="Inventory_Count" type="xsi:int"/>
            </xsi:sequence>
            <xsi:attribute name="id" type="xsi:ID" use="required"/>
          </xsi:complexType>
        </xsi:element>
      </xsi:sequence>
    </xsi:complexType>
  </xsi:element>
</xsi:schema>

=== youssef-souilah/StockMaster/data/products.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
  <Product id="product7631">
    <Name>On Cloud Nine Pillow</Name>
    <Price>24.99</Price>
    <Category>Home Decor</Category>
    <Brand>FabDecor</Brand>
    <Rating_Count>8</Rating_Count>
    <Inventory_Count>21</Inventory_Count>
  </Product>
  <Product id="product7632">
    <Name> Nine Pillow</Name>
    <Price>1000.99</Price>
    <Category>Home Decor</Category>
    <Brand>FabDecor</Brand>
    <Rating_Count>8</Rating_Count>
    <Inventory_Count>21</Inventory_Count>
  </Product>
  <Product id="product7633">
    <Name>Pillow</Name>
    <Price>50.99</Price>
    <Category>Home Decor</Category>
    <Brand>FabDecor</Brand>
    <Rating_Count>5</Rating_Count>
    <Inventory_Count>21</Inventory_Count>
  </Product>
  <Product id="produit2004">
    <Name>Hello</Name>
    <Price>100</Price>
    <Category>Electronics</Category>
    <Brand>Fs</Brand>
    <Rating_Count>8</Rating_Count>
    <Inventory_Count>10</Inventory_Count>
  </Product>
  <Product id="HELLO">
    <Name>NAME</Name>
    <Price>50</Price>
    <Category>Electronics</Category>
    <Brand>FD</Brand>
    <Rating_Count>5</Rating_Count>
    <Inventory_Count>70</Inventory_Count>
  </Product>
</Products>
